# TP03 – Python Librerías

## Fernández María Agustina

### Ejercicio 1 – Importación de librerías

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
datos = np.array([36, 11, 22, 41, 50])
print(datos)

[36 11 22 41 50]

In [3]:
alumnos=[
    ["Ana", 8],
    ["Juan", 6],
    ["Carla", 9],
    ["Pedro", 5],
    ["Lucia", 7]
]

df = pd.DataFrame(alumnos, columns=["Nombre", "Nota"])
df

  Nombre  Nota
0    Ana     8
1   Juan     6
2  Carla     9
3  Pedro     5
4  Lucia     7

In [5]:
df.describe()

           Nota
count  5.000000
mean   7.000000
std    1.581139
min    5.000000
25%    6.000000
50%    7.000000
75%    8.000000
max    9.000000

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=62bd93cc-1367-4433-a26d-e53b8483c5a0' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' />
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>